#!/usr/bin/env ruby

require "bundler/setup"
require "hekenga"
require "thor"

if File.exists?(File.expand_path("config/environment.rb"))
  require File.expand_path("config/environment.rb")
end

class HekengaCLI < Thor
  desc "run_all!", "Run all migrations that have not yet run, in date order."
  def run_all!
    # TODO
  end
  desc "run!", "Run a migration."
  def run!
    # TODO
  end
  desc "recover", "Attempt to resume a failed migration."
  def recover
    # TODO
  end
  desc "cancel", "Cancel all active migrations."
  def cancel
    # TODO
  end
  desc "status", "Show which migrations have run and their status."
  def status
    # TODO
  end
  desc "rollback", "Rollback a migration."
  def rollback
    # TODO
  end
  desc "cleanup", "Remove any failure logs."
  def cleanup
    # TODO
  end
end

HekengaCLI.start
